#%RAML 0.8
title: Housing Matching Service
version: 0.1.0
baseUri: http://server/api/{1.0}
mediaType: application/json
protocols: [ HTTP ]
/track:
  displayName: track clients and units
  /clients:
    displayName: track clients
    get:
      description: <<insert text or markdown here>>
  /units:
    description: track units
    get:
      description: <<insert text or markdown here>>
  