package com.survey;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Custom_Picklist.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CustomPicklistSurveymodel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** picklist_id. */
	private String picklistId;

	/** picklist_key. */
	private String picklistKey;

	/** picklist_value. */
	private String picklistValue;

	/** inactive. */
	private String inactive;

	/** date_created. */
	private Date dateCreated;

	/** date_updated. */
	private Date dateUpdated;

	/** user_id. */
	private String userId;

	/**
	 * Constructor.
	 */
	public CustomPicklistSurveymodel() {
	}

	/**
	 * Set the picklist_id.
	 * 
	 * @param picklistId
	 *            picklist_id
	 */
	public void setPicklistId(String picklistId) {
		this.picklistId = picklistId;
	}

	/**
	 * Get the picklist_id.
	 * 
	 * @return picklist_id
	 */
	public String getPicklistId() {
		return this.picklistId;
	}

	/**
	 * Set the picklist_key.
	 * 
	 * @param picklistKey
	 *            picklist_key
	 */
	public void setPicklistKey(String picklistKey) {
		this.picklistKey = picklistKey;
	}

	/**
	 * Get the picklist_key.
	 * 
	 * @return picklist_key
	 */
	public String getPicklistKey() {
		return this.picklistKey;
	}

	/**
	 * Set the picklist_value.
	 * 
	 * @param picklistValue
	 *            picklist_value
	 */
	public void setPicklistValue(String picklistValue) {
		this.picklistValue = picklistValue;
	}

	/**
	 * Get the picklist_value.
	 * 
	 * @return picklist_value
	 */
	public String getPicklistValue() {
		return this.picklistValue;
	}

	/**
	 * Set the inactive.
	 * 
	 * @param inactive
	 *            inactive
	 */
	public void setInactive(String inactive) {
		this.inactive = inactive;
	}

	/**
	 * Get the inactive.
	 * 
	 * @return inactive
	 */
	public String getInactive() {
		return this.inactive;
	}

	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	public Date getDateCreated() {
		return this.dateCreated;
	}

	/**
	 * Set the date_updated.
	 * 
	 * @param dateUpdated
	 *            date_updated
	 */
	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	/**
	 * Get the date_updated.
	 * 
	 * @return date_updated
	 */
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	/**
	 * Set the user_id.
	 * 
	 * @param userId
	 *            user_id
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the user_id.
	 * 
	 * @return user_id
	 */
	public String getUserId() {
		return this.userId;
	}


}
