package com.survey;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Survey.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SurveySurveymodel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** survey_id. */
	private String surveyId;

	/** survey_title. */
	private String surveyTitle;

	/** survey_owner. */
	private String surveyOwner;

	/** date_created. */
	private Date dateCreated;

	/** date_updated. */
	private Date dateUpdated;

	/** user_id. */
	private String userId;

	/** locked. */
	private String locked;

	/** inactive. */
	private String inactive;

	/** is_copysuvery_id. */
	private String isCopysuveryId;

	/** tag_valuestring. */
	private String tagValuestring;

	/** The set of Survey_Question. */
	private Set<SurveyQuestionSurveymodel> surveyQuestionSet;

	/**
	 * Constructor.
	 */
	public SurveySurveymodel() {
		this.surveyQuestionSet = new HashSet<SurveyQuestionSurveymodel>();
	}

	/**
	 * Set the survey_id.
	 * 
	 * @param surveyId
	 *            survey_id
	 */
	public void setSurveyId(String surveyId) {
		this.surveyId = surveyId;
	}

	/**
	 * Get the survey_id.
	 * 
	 * @return survey_id
	 */
	public String getSurveyId() {
		return this.surveyId;
	}

	/**
	 * Set the survey_title.
	 * 
	 * @param surveyTitle
	 *            survey_title
	 */
	public void setSurveyTitle(String surveyTitle) {
		this.surveyTitle = surveyTitle;
	}

	/**
	 * Get the survey_title.
	 * 
	 * @return survey_title
	 */
	public String getSurveyTitle() {
		return this.surveyTitle;
	}

	/**
	 * Set the survey_owner.
	 * 
	 * @param surveyOwner
	 *            survey_owner
	 */
	public void setSurveyOwner(String surveyOwner) {
		this.surveyOwner = surveyOwner;
	}

	/**
	 * Get the survey_owner.
	 * 
	 * @return survey_owner
	 */
	public String getSurveyOwner() {
		return this.surveyOwner;
	}

	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	public Date getDateCreated() {
		return this.dateCreated;
	}

	/**
	 * Set the date_updated.
	 * 
	 * @param dateUpdated
	 *            date_updated
	 */
	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	/**
	 * Get the date_updated.
	 * 
	 * @return date_updated
	 */
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	/**
	 * Set the user_id.
	 * 
	 * @param userId
	 *            user_id
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the user_id.
	 * 
	 * @return user_id
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * Set the locked.
	 * 
	 * @param locked
	 *            locked
	 */
	public void setLocked(String locked) {
		this.locked = locked;
	}

	/**
	 * Get the locked.
	 * 
	 * @return locked
	 */
	public String getLocked() {
		return this.locked;
	}

	/**
	 * Set the inactive.
	 * 
	 * @param inactive
	 *            inactive
	 */
	public void setInactive(String inactive) {
		this.inactive = inactive;
	}

	/**
	 * Get the inactive.
	 * 
	 * @return inactive
	 */
	public String getInactive() {
		return this.inactive;
	}

	/**
	 * Set the is_copysuvery_id.
	 * 
	 * @param isCopysuveryId
	 *            is_copysuvery_id
	 */
	public void setIsCopysuveryId(String isCopysuveryId) {
		this.isCopysuveryId = isCopysuveryId;
	}

	/**
	 * Get the is_copysuvery_id.
	 * 
	 * @return is_copysuvery_id
	 */
	public String getIsCopysuveryId() {
		return this.isCopysuveryId;
	}

	/**
	 * Set the tag_valuestring.
	 * 
	 * @param tagValuestring
	 *            tag_valuestring
	 */
	public void setTagValuestring(String tagValuestring) {
		this.tagValuestring = tagValuestring;
	}

	/**
	 * Get the tag_valuestring.
	 * 
	 * @return tag_valuestring
	 */
	public String getTagValuestring() {
		return this.tagValuestring;
	}

	/**
	 * Set the set of the Survey_Question.
	 * 
	 * @param surveyQuestionSet
	 *            The set of Survey_Question
	 */
	public void setSurveyQuestionSet(Set<SurveyQuestionSurveymodel> surveyQuestionSet) {
		this.surveyQuestionSet = surveyQuestionSet;
	}

	/**
	 * Add the Survey_Question.
	 * 
	 * @param surveyQuestion
	 *            Survey_Question
	 */
	public void addSurveyQuestion(SurveyQuestionSurveymodel surveyQuestion) {
		this.surveyQuestionSet.add(surveyQuestion);
	}

	/**
	 * Get the set of the Survey_Question.
	 * 
	 * @return The set of Survey_Question
	 */
	public Set<SurveyQuestionSurveymodel> getSurveyQuestionSet() {
		return this.surveyQuestionSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((surveyId == null) ? 0 : surveyId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SurveySurveymodel other = (SurveySurveymodel) obj;
		if (surveyId == null) {
			if (other.surveyId != null) {
				return false;
			}
		} else if (!surveyId.equals(other.surveyId)) {
			return false;
		}
		return true;
	}

}
