package com.hserv.coordinatedentry.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Model class of Custom_Picklist.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
public class CustomPicklist implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** picklist_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	// @GeneratedValue(strategy=GenerationType.IDENTITY,
	// generator="picklist_id_seq")
	// @SequenceGenerator(name="picklist_id_seq",
	// sequenceName="picklist_id_seq")
	private Integer picklistId;

	/** picklist_key. */
	private String picklistKey;

	/** picklist_value. */
	private String picklistValue;

	/** inactive. */
	private Boolean inactive;

	/** date_created. */
	@JsonIgnore
	private Date dateCreated;

	/** date_updated. */
	@JsonIgnore
	private Date dateUpdated;

	/** user_id. */
	private String userId;

	@ManyToOne
	@JoinColumn(name="question_fk_id")
	@JsonBackReference
	private Question question;
	/**
	 * Constructor.
	 */
	public CustomPicklist() {
	}

	public Integer getPicklistId() {
		return picklistId;
	}

	public void setPicklistId(Integer picklistId) {
		this.picklistId = picklistId;
	}

	/**
	 * Set the picklist_key.
	 * 
	 * @param picklistKey
	 *            picklist_key
	 */
	public void setPicklistKey(String picklistKey) {
		this.picklistKey = picklistKey;
	}

	/**
	 * Get the picklist_key.
	 * 
	 * @return picklist_key
	 */
	public String getPicklistKey() {
		return this.picklistKey;
	}

	/**
	 * Set the picklist_value.
	 * 
	 * @param picklistValue
	 *            picklist_value
	 */
	public void setPicklistValue(String picklistValue) {
		this.picklistValue = picklistValue;
	}

	/**
	 * Get the picklist_value.
	 * 
	 * @return picklist_value
	 */
	public String getPicklistValue() {
		return this.picklistValue;
	}

	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	public Date getDateCreated() {
		return this.dateCreated;
	}

	/**
	 * Set the date_updated.
	 * 
	 * @param dateUpdated
	 *            date_updated
	 */
	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	/**
	 * Get the date_updated.
	 * 
	 * @return date_updated
	 */
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public Boolean getInactive() {
		return inactive;
	}

	public void setInactive(Boolean inactive) {
		this.inactive = inactive;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Question getQuestion() {
		return question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

}
