package com.hserv.coordinatedentry.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Model class of Response_Storage.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
public class ResponseStorage implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** survey_question_id. */
	private String surveyQuestionId;

	/** response_value. */
	private String responseValue;

	/** response_subassessment. */
	private String responseSubassessment;

	@Id
	// @GeneratedValue(strategy=GenerationType.SEQUENCE,
	// generator="client_Id_seq")
	// @SequenceGenerator(name="client_Id_seq", sequenceName="client_Id_seq")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer clientId;

	/** app_id. */
	private String appId;

	/** effective_date. */
	private Date effectiveDate;

	/** date_created. */
	private Date dateCreated;

	/** date_updated. */
	private Date dateUpdated;

	/** user_id. */
	private String userId;
	
	/** section_id. */
	private String sectionId;

	/**
	 * Constructor.
	 */
	public ResponseStorage() {
	}

	/**
	 * Set the response_value.
	 * 
	 * @param responseValue
	 *            response_value
	 */
	public void setResponseValue(String responseValue) {
		this.responseValue = responseValue;
	}

	/**
	 * Get the response_value.
	 * 
	 * @return response_value
	 */
	public String getResponseValue() {
		return this.responseValue;
	}

	/**
	 * Set the response_subassessment.
	 * 
	 * @param responseSubassessment
	 *            response_subassessment
	 */
	public void setResponseSubassessment(String responseSubassessment) {
		this.responseSubassessment = responseSubassessment;
	}

	/**
	 * Get the response_subassessment.
	 * 
	 * @return response_subassessment
	 */
	public String getResponseSubassessment() {
		return this.responseSubassessment;
	}

	public Integer getClientId() {
		return clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	/**
	 * Set the app_id.
	 * 
	 * @param appId
	 *            app_id
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * Get the app_id.
	 * 
	 * @return app_id
	 */
	public String getAppId() {
		return this.appId;
	}

	/**
	 * Set the effective_date.
	 * 
	 * @param effectiveDate
	 *            effective_date
	 */
	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	/**
	 * Get the effective_date.
	 * 
	 * @return effective_date
	 */
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	public Date getDateCreated() {
		return this.dateCreated;
	}

	/**
	 * Set the date_updated.
	 * 
	 * @param dateUpdated
	 *            date_updated
	 */
	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	/**
	 * Get the date_updated.
	 * 
	 * @return date_updated
	 */
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public String getSurveyQuestionId() {
		return surveyQuestionId;
	}

	public void setSurveyQuestionId(String surveyQuestionId) {
		this.surveyQuestionId = surveyQuestionId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getSectionId() {
		return sectionId;
	}

	public void setSectionId(String sectionId) {
		this.sectionId = sectionId;
	}

}
