package com.hserv.coordinatedentry.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Model class of Response_Type.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
public class ResponseType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
	// @GeneratedValue(strategy=GenerationType.SEQUENCE,
	// generator="response_type_id_seq")
	// @SequenceGenerator(name="response_type_id_seq",
	// sequenceName="response_type_id_seq")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer responseTypeId;

	/** hmis_response. */
	private String hmisResponse;

	/** text. */
	private String text;

	/** integer. */
	@Column(name = "count")
	private Integer integer;

	/** currency. */
	private Float currency;

	/** custom_picklist. */
	private Boolean customPicklist;

	/** multiple_select. */
	private Boolean multipleSelect;

	/** max_select. */
	private String maxSelect;

	/** subassessment_survey_id. */
	private String subassessmentSurveyId;

	/** date_created. */
	private Date dateCreated;

	/** date_updated. */
	private Date dateUpdated;

	/** user_id. */
	private String userId;

	/**
	 * Constructor.
	 */
	public ResponseType() {
	}

	public Integer getResponseTypeId() {
		return responseTypeId;
	}

	public void setResponseTypeId(Integer responseTypeId) {
		this.responseTypeId = responseTypeId;
	}

	/**
	 * Set the hmis_response.
	 * 
	 * @param hmisResponse
	 *            hmis_response
	 */
	public void setHmisResponse(String hmisResponse) {
		this.hmisResponse = hmisResponse;
	}

	/**
	 * Get the hmis_response.
	 * 
	 * @return hmis_response
	 */
	public String getHmisResponse() {
		return this.hmisResponse;
	}

	/**
	 * Set the text.
	 * 
	 * @param text
	 *            text
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * Get the text.
	 * 
	 * @return text
	 */
	public String getText() {
		return this.text;
	}

	public Integer getInteger() {
		return integer;
	}

	public void setInteger(Integer integer) {
		this.integer = integer;
	}

	public Float getCurrency() {
		return currency;
	}

	public void setCurrency(Float currency) {
		this.currency = currency;
	}

	public Boolean getCustomPicklist() {
		return customPicklist;
	}

	public void setCustomPicklist(Boolean customPicklist) {
		this.customPicklist = customPicklist;
	}

	public Boolean getMultipleSelect() {
		return multipleSelect;
	}

	public void setMultipleSelect(Boolean multipleSelect) {
		this.multipleSelect = multipleSelect;
	}

	public String getSubassessmentSurveyId() {
		return subassessmentSurveyId;
	}

	public void setSubassessmentSurveyId(String subassessmentSurveyId) {
		this.subassessmentSurveyId = subassessmentSurveyId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Set the max_select.
	 * 
	 * @param maxSelect
	 *            max_select
	 */
	public void setMaxSelect(String maxSelect) {
		this.maxSelect = maxSelect;
	}

	/**
	 * Get the max_select.
	 * 
	 * @return max_select
	 */
	public String getMaxSelect() {
		return this.maxSelect;
	}

	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	public Date getDateCreated() {
		return this.dateCreated;
	}

	/**
	 * Set the date_updated.
	 * 
	 * @param dateUpdated
	 *            date_updated
	 */
	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	/**
	 * Get the date_updated.
	 * 
	 * @return date_updated
	 */
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

}
