
package com.hserv.coordinatedentry.housingmatching.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(value = "/coordinatedentry/matches", produces = "application/json")
public class MatchController {

	/**
	 * Use this API to trigger the matching process once score calculation is
	 * done. Posting an empty body would suffice.
	 * 
	 * 
	 */
	@RequestMapping(value = "", method = RequestMethod.POST)
	public ResponseEntity createMatch() {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Get the list of the proposed matches.
	 * 
	 */
	@RequestMapping(value = "", method = RequestMethod.GET)
	public ResponseEntity getMatches() {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Clear all the proposed matches.
	 * 
	 * 
	 */
	@RequestMapping(value = "", method = RequestMethod.DELETE)
	public ResponseEntity deleteMatches() {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Get the proposed matche for a client_id.
	 * 
	 */
	@RequestMapping(value = "/client/{id}", method = RequestMethod.GET)
	public ResponseEntity getClientById(@PathVariable String id) {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Clears off the proposed match for a particular client.
	 * 
	 * 
	 */
	@RequestMapping(value = "/client/{id}", method = RequestMethod.DELETE)
	public ResponseEntity deleteClientById(@PathVariable String id) {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Used for updating/accepting the match for a client id.
	 * This method will be called as and when the Admin approves or
	 *  reject the housing match for client
	 * 
	 */
	@RequestMapping(value = "/client/{id}", method = RequestMethod.PUT)
	public ResponseEntity updateClientById(@PathVariable String id) {
		//call DB layer to update match_reservation table with match_status
		//as approve or rejected based on the input value
		//if input value is approve/yes then only
		//call notification service to notify housing unit/user/client
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

}
