
package com.hserv.coordinatedentry.housingmatching.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.hserv.coordinatedentry.housingmatching.dao.EligibleClientsRepository;

@RestController
@ResponseBody
@RequestMapping(value = "/scores", produces = "application/json")
public class ScoreController {
	
	@Autowired
	private EligibleClientsRepository eligibleClientRepository;

	/**
	 * Trigger score totalling via POST. An Empty body request would suffice.
	 * 
	 * 
	 */
	@RequestMapping(value = "", method = RequestMethod.POST)
	public ResponseEntity createScore() {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Get the list of clients and their survey scores.
	 * 
	 */
	@RequestMapping(value = "", method = RequestMethod.GET)
	public ResponseEntity getScores() {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Clear all the survey scores.
	 * 
	 * 
	 */
	@RequestMapping(value = "", method = RequestMethod.DELETE)
	public ResponseEntity deleteScores() {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Get the survey score for a client_id.
	 * 
	 */
	@RequestMapping(value = "/client/{id}", method = RequestMethod.GET)
	public ResponseEntity getClientById(@PathVariable String id) {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Clears off the survey score for a particular client.
	 * 
	 * 
	 */
	@RequestMapping(value = "/client/{id}", method = RequestMethod.DELETE)
	public ResponseEntity deleteClientById(@PathVariable String id) {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

	/**
	 * Used for updating survey score for a client id.
	 * 
	 * 
	 */
	@RequestMapping(value = "/client/{id}", method = RequestMethod.PUT)
	public ResponseEntity updateClientById(@PathVariable String id) {
		return null; // TODO Autogenerated Method Stub. Implement me please.
	}

}
