package com.hserv.coordinatedentry.housingmatching.facade;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.hserv.coordinatedentry.housingmatching.model.CommunityPreferenceInfoModel;
import com.hserv.coordinatedentry.housingmatching.model.EligibleClientModel;
import com.hserv.coordinatedentry.housingmatching.model.HousingInventoryModel;
import com.hserv.coordinatedentry.housingmatching.model.ProjectEligibilityInfoModel;
import com.hserv.coordinatedentry.housingmatching.service.CommunityPreferenceService;
import com.hserv.coordinatedentry.housingmatching.service.EligibleClientService;
import com.hserv.coordinatedentry.housingmatching.service.HousingUnitService;
import com.hserv.coordinatedentry.housingmatching.service.ProjectEligibilityInfoService;

@Component
public class MatchFacade {
	
	@Autowired
	private ProjectEligibilityInfoService projectEligibilityInfoService;
	
	@Autowired
	private CommunityPreferenceService communityPreferenceService;
	
	@Autowired
	private HousingUnitService housingUnitService;
	
	@Autowired
	private EligibleClientService eligibleClientService;
	
	public void createMatch(String userId) {
		//TODO validate user
		
		//1. get project eligibility
		List<ProjectEligibilityInfoModel> eligibleProjectsInfo = projectEligibilityInfoService.getEligibleProjectsInfo();
		
		//2. get community preferences
		List<CommunityPreferenceInfoModel> communityPreferenceInfo = communityPreferenceService.getCommunityPrerences();
		
		//3. get available housing units
		List<HousingInventoryModel> housingInventoryModels = housingUnitService.getHousingInventoryList(userId);
		
		//4. Get top n eligible clients
		//5. criteria -> 1) ,2),3)
		int count = 10;
		List<EligibleClientModel> eligibleClientModels = eligibleClientService.getEligibleClients(10);
		
		//6. call auto-matching algorithm to get right match
		
		//7. check the county 
		
		//8. if county is monterey - 
		//9. call DB layer to update match_reservation table with match_status as success
		//10. Call Notification service for Admin to approve or reject
		
		//11. if county is non monterey 
		//12. call DB layer to update match_reservation table with match_status as approve
		//13. Call Notification service to notify housing unit and client
		//return null; // TODO Autogenerated Method Stub. Implement me please.
	}
	

}
