package app.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * Model class of Response_Type.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
public class ResponseType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
//	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="response_type_id_seq")
//	@SequenceGenerator(name="response_type_id_seq", sequenceName="response_type_id_seq")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer responseTypeId;

	/** hmis_response. */
	private String hmisResponse;

	/** text. */
	private String text;

	/** integer. */
	@Column(name="count")
	private String integer;

	/** currency. */
	private String currency;

	/** custom_picklist. */
	private String customPicklist;

	/** multiple_select. */
	private String multipleSelect;

	/** max_select. */
	private String maxSelect;

	/** subassessment_survey_id. */
	private String subassessmentSurveyId;

	/** date_created. */
	private Date dateCreated;

	/** date_updated. */
	private Date dateUpdated;

	/** user_id. */
	private String userId;

	/**
	 * Constructor.
	 */
	public ResponseType() {
	}


	public Integer getResponseTypeId() {
		return responseTypeId;
	}


	public void setResponseTypeId(Integer responseTypeId) {
		this.responseTypeId = responseTypeId;
	}


	/**
	 * Set the hmis_response.
	 * 
	 * @param hmisResponse
	 *            hmis_response
	 */
	public void setHmisResponse(String hmisResponse) {
		this.hmisResponse = hmisResponse;
	}

	/**
	 * Get the hmis_response.
	 * 
	 * @return hmis_response
	 */
	public String getHmisResponse() {
		return this.hmisResponse;
	}

	/**
	 * Set the text.
	 * 
	 * @param text
	 *            text
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * Get the text.
	 * 
	 * @return text
	 */
	public String getText() {
		return this.text;
	}

	/**
	 * Set the integer.
	 * 
	 * @param integer
	 *            integer
	 */
	public void setInteger(String integer) {
		this.integer = integer;
	}

	/**
	 * Get the integer.
	 * 
	 * @return integer
	 */
	public String getInteger() {
		return this.integer;
	}

	/**
	 * Set the currency.
	 * 
	 * @param currency
	 *            currency
	 */
	public void setCurrency(String currency) {
		this.currency = currency;
	}

	/**
	 * Get the currency.
	 * 
	 * @return currency
	 */
	public String getCurrency() {
		return this.currency;
	}

	/**
	 * Set the custom_picklist.
	 * 
	 * @param customPicklist
	 *            custom_picklist
	 */
	public void setCustomPicklist(String customPicklist) {
		this.customPicklist = customPicklist;
	}

	/**
	 * Get the custom_picklist.
	 * 
	 * @return custom_picklist
	 */
	public String getCustomPicklist() {
		return this.customPicklist;
	}

	/**
	 * Set the multiple_select.
	 * 
	 * @param multipleSelect
	 *            multiple_select
	 */
	public void setMultipleSelect(String multipleSelect) {
		this.multipleSelect = multipleSelect;
	}

	/**
	 * Get the multiple_select.
	 * 
	 * @return multiple_select
	 */
	public String getMultipleSelect() {
		return this.multipleSelect;
	}

	/**
	 * Set the max_select.
	 * 
	 * @param maxSelect
	 *            max_select
	 */
	public void setMaxSelect(String maxSelect) {
		this.maxSelect = maxSelect;
	}

	/**
	 * Get the max_select.
	 * 
	 * @return max_select
	 */
	public String getMaxSelect() {
		return this.maxSelect;
	}

	/**
	 * Set the subassessment_survey_id.
	 * 
	 * @param subassessmentSurveyId
	 *            subassessment_survey_id
	 */
	public void setSubassessmentSurveyId(String subassessmentSurveyId) {
		this.subassessmentSurveyId = subassessmentSurveyId;
	}

	/**
	 * Get the subassessment_survey_id.
	 * 
	 * @return subassessment_survey_id
	 */
	public String getSubassessmentSurveyId() {
		return this.subassessmentSurveyId;
	}

	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	public Date getDateCreated() {
		return this.dateCreated;
	}

	/**
	 * Set the date_updated.
	 * 
	 * @param dateUpdated
	 *            date_updated
	 */
	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	/**
	 * Get the date_updated.
	 * 
	 * @return date_updated
	 */
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	/**
	 * Set the user_id.
	 * 
	 * @param userId
	 *            user_id
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the user_id.
	 * 
	 * @return user_id
	 */
	public String getUserId() {
		return this.userId;
	}


}
