package app.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Model class of Survey.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
public class Survey implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** survey_id. */
	@Id
//	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="survey_id_seq")
//	@SequenceGenerator(name="survey_id_seq", sequenceName="survey_id_seq")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer surveyId;

	/** survey_title. */
	private String surveyTitle;

	/** survey_owner. */
	private String surveyOwner;

	/** date_created. */
	private String dateCreated;

	/** date_updated. */
	private String dateUpdated;

	/** user_id. */
	private String userId;

	/** locked. */
	private Boolean locked;

	/** inactive. */
	private String inactive;

	/** is_copysuvery_id. */
	private Integer copySuveryId;

	/** tag_valuestring. */
	private String tagValue;

	/** The set of Survey_Question. */
	@OneToMany(mappedBy="survey", cascade=CascadeType.ALL)
	@JsonManagedReference
	private List<SurveyQuestion> surveyQuestion;

	/**
	 * Constructor.
	 */
	public Survey() {
		this.surveyQuestion = new ArrayList<SurveyQuestion>();
	}


	public Integer getSurveyId() {
		return surveyId;
	}


	public void setSurveyId(Integer surveyId) {
		this.surveyId = surveyId;
	}


	/**
	 * Set the survey_title.
	 * 
	 * @param surveyTitle
	 *            survey_title
	 */
	public void setSurveyTitle(String surveyTitle) {
		this.surveyTitle = surveyTitle;
	}

	/**
	 * Get the survey_title.
	 * 
	 * @return survey_title
	 */
	public String getSurveyTitle() {
		return this.surveyTitle;
	}

	/**
	 * Set the survey_owner.
	 * 
	 * @param surveyOwner
	 *            survey_owner
	 */
	public void setSurveyOwner(String surveyOwner) {
		this.surveyOwner = surveyOwner;
	}

	/**
	 * Get the survey_owner.
	 * 
	 * @return survey_owner
	 */
	public String getSurveyOwner() {
		return this.surveyOwner;
	}

	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(String dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	public String getDateCreated() {
		return this.dateCreated;
	}

	/**
	 * Set the date_updated.
	 * 
	 * @param dateUpdated
	 *            date_updated
	 */
	public void setDateUpdated(String dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	/**
	 * Get the date_updated.
	 * 
	 * @return date_updated
	 */
	public String getDateUpdated() {
		return this.dateUpdated;
	}

	/**
	 * Set the user_id.
	 * 
	 * @param userId
	 *            user_id
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the user_id.
	 * 
	 * @return user_id
	 */
	public String getUserId() {
		return this.userId;
	}

	public Boolean getLocked() {
		return locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}


	/**
	 * Set the inactive.
	 * 
	 * @param inactive
	 *            inactive
	 */
	public void setInactive(String inactive) {
		this.inactive = inactive;
	}

	/**
	 * Get the inactive.
	 * 
	 * @return inactive
	 */
	public String getInactive() {
		return this.inactive;
	}



	public Integer getCopySuveryId() {
		return copySuveryId;
	}


	public void setCopySuveryId(Integer copySuveryId) {
		this.copySuveryId = copySuveryId;
	}


	/**
	 * Set the tag_valuestring.
	 * 
	 * @param tagValuestring
	 *            tag_valuestring
	 */
	public void setTagValuestring(String tagValue) {
		this.tagValue = tagValue;
	}

	/**
	 * Get the tag_valuestring.
	 * 
	 * @return tag_valuestring
	 */
	public String getTagValuestring() {
		return this.tagValue;
	}

	/**
	 * Set the set of the Survey_Question.
	 * 
	 * @param surveyQuestionSet
	 *            The set of Survey_Question
	 */
	public void setSurveyQuestion(List<SurveyQuestion> surveyQuestion) {
		this.surveyQuestion = surveyQuestion;
	}

	/**
	 * Add the Survey_Question.
	 * 
	 * @param surveyQuestion
	 *            Survey_Question
	 */
	public void addSurveyQuestion(SurveyQuestion surveyQuestion) {
		this.surveyQuestion.add(surveyQuestion);
	}

	/**
	 * Get the set of the Survey_Question.
	 * 
	 * @return The set of Survey_Question
	 */
	public List<SurveyQuestion> getSurveyQuestion() {
		return this.surveyQuestion;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((surveyId == null) ? 0 : surveyId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Survey other = (Survey) obj;
		if (surveyId == null) {
			if (other.surveyId != null) {
				return false;
			}
		} else if (!surveyId.equals(other.surveyId)) {
			return false;
		}
		return true;
	}

}
