package com.survey;

import java.io.Serializable;

/**
 * Model class of label_picklist.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class LabelPicklistSurveymodel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** index. */
	private String index;

	/** label_value. */
	private String labelValue;

	/**
	 * Constructor.
	 */
	public LabelPicklistSurveymodel() {
	}

	/**
	 * Set the index.
	 * 
	 * @param index
	 *            index
	 */
	public void setIndex(String index) {
		this.index = index;
	}

	/**
	 * Get the index.
	 * 
	 * @return index
	 */
	public String getIndex() {
		return this.index;
	}

	/**
	 * Set the label_value.
	 * 
	 * @param labelValue
	 *            label_value
	 */
	public void setLabelValue(String labelValue) {
		this.labelValue = labelValue;
	}

	/**
	 * Get the label_value.
	 * 
	 * @return label_value
	 */
	public String getLabelValue() {
		return this.labelValue;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((index == null) ? 0 : index.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		LabelPicklistSurveymodel other = (LabelPicklistSurveymodel) obj;
		if (index == null) {
			if (other.index != null) {
				return false;
			}
		} else if (!index.equals(other.index)) {
			return false;
		}
		return true;
	}

}
