package com.survey;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Survey_Question.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SurveyQuestionSurveymodel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** survey_question_id. */
	private String surveyQuestionId;

	/** survey_id. */
	private String surveyId;

	/** question_id. */
	private String questionId;

	/** question_parent. */
	private String questionParent;

	/** question_child. */
	private String questionChild;

	/** required. */
	private String required;

	/** date_created. */
	private Date dateCreated;

	/** date_updated. */
	private Date dateUpdated;

	/** user_id. */
	private String userId;

	/** Survey. */
	private SurveySurveymodel survey;

	/** Question. */
	private QuestionSurveymodel question;

	/**
	 * Constructor.
	 */
	public SurveyQuestionSurveymodel() {
	}

	/**
	 * Set the survey_question_id.
	 * 
	 * @param surveyQuestionId
	 *            survey_question_id
	 */
	public void setSurveyQuestionId(String surveyQuestionId) {
		this.surveyQuestionId = surveyQuestionId;
	}

	/**
	 * Get the survey_question_id.
	 * 
	 * @return survey_question_id
	 */
	public String getSurveyQuestionId() {
		return this.surveyQuestionId;
	}

	/**
	 * Set the survey_id.
	 * 
	 * @param surveyId
	 *            survey_id
	 */
	public void setSurveyId(String surveyId) {
		this.surveyId = surveyId;
	}

	/**
	 * Get the survey_id.
	 * 
	 * @return survey_id
	 */
	public String getSurveyId() {
		return this.surveyId;
	}

	/**
	 * Set the question_id.
	 * 
	 * @param questionId
	 *            question_id
	 */
	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	/**
	 * Get the question_id.
	 * 
	 * @return question_id
	 */
	public String getQuestionId() {
		return this.questionId;
	}

	/**
	 * Set the question_parent.
	 * 
	 * @param questionParent
	 *            question_parent
	 */
	public void setQuestionParent(String questionParent) {
		this.questionParent = questionParent;
	}

	/**
	 * Get the question_parent.
	 * 
	 * @return question_parent
	 */
	public String getQuestionParent() {
		return this.questionParent;
	}

	/**
	 * Set the question_child.
	 * 
	 * @param questionChild
	 *            question_child
	 */
	public void setQuestionChild(String questionChild) {
		this.questionChild = questionChild;
	}

	/**
	 * Get the question_child.
	 * 
	 * @return question_child
	 */
	public String getQuestionChild() {
		return this.questionChild;
	}

	/**
	 * Set the required.
	 * 
	 * @param required
	 *            required
	 */
	public void setRequired(String required) {
		this.required = required;
	}

	/**
	 * Get the required.
	 * 
	 * @return required
	 */
	public String getRequired() {
		return this.required;
	}

	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	public Date getDateCreated() {
		return this.dateCreated;
	}

	/**
	 * Set the date_updated.
	 * 
	 * @param dateUpdated
	 *            date_updated
	 */
	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	/**
	 * Get the date_updated.
	 * 
	 * @return date_updated
	 */
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	/**
	 * Set the user_id.
	 * 
	 * @param userId
	 *            user_id
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the user_id.
	 * 
	 * @return user_id
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * Set the Survey.
	 * 
	 * @param survey
	 *            Survey
	 */
	public void setSurvey(SurveySurveymodel survey) {
		this.survey = survey;
	}

	/**
	 * Get the Survey.
	 * 
	 * @return Survey
	 */
	public SurveySurveymodel getSurvey() {
		return this.survey;
	}

	/**
	 * Set the Question.
	 * 
	 * @param question
	 *            Question
	 */
	public void setQuestion(QuestionSurveymodel question) {
		this.question = question;
	}

	/**
	 * Get the Question.
	 * 
	 * @return Question
	 */
	public QuestionSurveymodel getQuestion() {
		return this.question;
	}


}
